services:
  # VS Code workspace service
  workspace:
    image: ghcr.io/tigrisdata-community/warpstream-tigris/devcontainer
    build:
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/workspace:cached
    # entrypoint: ["/usr/bin/sleep", "infinity"]
    user: vscode
